apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: github-apicurio-registry-nxsh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-apicurio-registry-nxsh
    app.kubernetes.io/part-of: my-app
  name: github-apicurio-registry-nxsh
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: github-apicurio-registry-nxsh
status:
  loadBalancer: {}
