apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: app-apicurio-registry-pa4d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app-apicurio-registry-pa4d
    app.kubernetes.io/part-of: my-app
  name: app-apicurio-registry-pa4d
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: app-apicurio-registry-pa4d
status:
  loadBalancer: {}
