apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: serdes-apicurio-registry-abty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serdes-apicurio-registry-abty
    app.kubernetes.io/part-of: my-app
  name: serdes-apicurio-registry-abty
  namespace: munahaf-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: serdes-apicurio-registry-abty
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: serdes-apicurio-registry-abty
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:dKWyF-serdes-apicurio-registry-abty
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
