apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: serdes-apicurio-registry-abty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serdes-apicurio-registry-abty
    app.kubernetes.io/part-of: my-app
  name: serdes-apicurio-registry-abty
  namespace: munahaf-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: serdes-apicurio-registry-abty
    weight: null
status: {}
