apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-system-tests-apicurio-registry-kihk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-system-tests-apicurio-registry-kihk
    app.kubernetes.io/part-of: my-app
  name: new-system-tests-apicurio-registry-kihk
  namespace: munahaf-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: new-system-tests-apicurio-registry-kihk
    weight: null
status: {}
