apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: new-system-tests-apicurio-registry-kihk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: new-system-tests-apicurio-registry-kihk
    app.kubernetes.io/part-of: my-app
  name: new-system-tests-apicurio-registry-kihk
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: new-system-tests-apicurio-registry-kihk
status:
  loadBalancer: {}
