apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: storage-apicurio-registry-mopv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: storage-apicurio-registry-mopv
    app.kubernetes.io/part-of: my-app
  name: storage-apicurio-registry-mopv
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: storage-apicurio-registry-mopv
status:
  loadBalancer: {}
