apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: utils-apicurio-registry-qqjy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: utils-apicurio-registry-qqjy
    app.kubernetes.io/part-of: my-app
  name: utils-apicurio-registry-qqjy
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: utils-apicurio-registry-qqjy
status:
  loadBalancer: {}
