apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-apicurio-registry-bgwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-apicurio-registry-bgwz
    app.kubernetes.io/part-of: my-app
  name: common-apicurio-registry-bgwz
  namespace: munahaf-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: common-apicurio-registry-bgwz
    weight: null
status: {}
