apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: docs-apicurio-registry-kd5b
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: docs-apicurio-registry-kd5b
    app.kubernetes.io/part-of: my-app
  name: docs-apicurio-registry-kd5b
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: docs-apicurio-registry-kd5b
status:
  loadBalancer: {}
