apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: distro-apicurio-registry-oycm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: distro-apicurio-registry-oycm
    app.kubernetes.io/part-of: my-app
  name: distro-apicurio-registry-oycm
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: distro-apicurio-registry-oycm
status:
  loadBalancer: {}
