apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: schema-util-apicurio-registry-3zvs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: schema-util-apicurio-registry-3zvs
    app.kubernetes.io/part-of: my-app
  name: schema-util-apicurio-registry-3zvs
  namespace: munahaf-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: schema-util-apicurio-registry-3zvs
    weight: null
status: {}
