apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-tests-apicurio-registry-vd5j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-tests-apicurio-registry-vd5j
    app.kubernetes.io/part-of: my-app
  name: integration-tests-apicurio-registry-vd5j
  namespace: munahaf-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: integration-tests-apicurio-registry-vd5j
status:
  loadBalancer: {}
